name: flutter_application_1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^29.1.41
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - images/
